on:
  push:
    paths:
      - "src/**"
name: Run linting and unit tests on push
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.rustfmt.outputs.src }}
      infra: ${{ steps.rustfmt.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy --all -- -W warnings
